name: Release and Publish
on:
  push:
    branches:
      - alpha
jobs:
  semantic-release:
    name: Run Release
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_USERNAME: lime-ci
      GH_TOKEN: ${{ secrets.CREATE_RELEASE }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_ads }}
      GIT_AUTHOR_NAME: lime-ci
      GIT_AUTHOR_EMAIL: 617355+lime-ci@users.noreply.github.com
      CI: true
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: ./release-alpha.sh
